[common]
build_unflags_shared = -std=gnu++11
build_flags_shared = -std=gnu++17
    -Wall
    -Werror

[env:ttgo-t1-arduino]
platform = espressif32
board = ttgo-t1
framework = arduino
upload_speed = 921600
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
extra_scripts = pre:buffers_extra.py
lib_deps = codewitch-honey-crisis/htcw_frame_arq
build_unflags = ${common.build_unflags_shared}
build_flags = ${common.build_flags_shared}
    -DTTGO_T1
;upload_port=COM23
